language: node_js
sudo: false
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt
  - npm test
  - jscoverage lib --exclude *.ejs,*.json && NIGHTWATCH_COV=1 node ./tests/run_tests.js lcov > ./lib-cov/lcov.info

after_success:
  - cat ./lib-cov/lcov.info |coveralls

